// Back-compat shim: the provider-aware implementation lives in ./llm.mjs.
export {
  applyLocalOpenAISettingsFromStore,
  getLocalOpenAIConfig,
  getLocalOpenAIKey,
  isLocalOpenAIConfigured,
  normalizeLocalOpenAISettingsRecord,
  publicLocalOpenAISettings,
  updateLocalOpenAISettings,
  applyLocalLLMSettingsFromStore,
  getLocalLLMApiKey,
  getLocalLLMConfig,
  isLocalLLMConfigured,
  normalizeLocalLLMSettingsRecord,
  publicLocalLLMSettings,
  updateLocalLLMSettings,
  generateChatReply,
  generateLocalAgentRunSummaryWithOpenAI,
  generateLocalAgentSessionSummaryWithOpenAI,
  generateLocalCommandCenterTitle,
  generateLocalExecutiveSummaryWithOpenAI,
  generateLocalExternalAgentExecutionContextWithOpenAI,
  generateLocalWorkflowEmailWithOpenAI,
  generateLocalWorkflowSummaryWithOpenAI,
  refineLocalWorkloadDiscoveryWithOpenAI,
} from "./llm.mjs";
